stages:
    - test

.test: &test_template
    stage: test
    script:
        - go test -cover -race ./...

linter:
  stage: test
  image: golangci/golangci-lint:v1.22
  script:
    - go mod download
    - golangci-lint run ./...

go-1.13:
    <<: *test_template
    stage: test
    image: golang:1.13

go-rc:
    <<: *test_template
    stage: test
    image: golang:rc
    allow_failure: true
